/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author KauaValim
 */
public class fInterface extends javax.swing.JFrame {

    /**
     * Creates new form fInterface
     */
    public fInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGeneros = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbGenre = new javax.swing.JLabel();
        txtBornDate = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnConsult = new javax.swing.JButton();
        rbtFemale = new javax.swing.JRadioButton();
        rbtMale = new javax.swing.JRadioButton();
        lbBornDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 100, 211), 20));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(810, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/guru.png"))); // NOI18N
        jLabel1.setText(" Guru Online");
        jLabel1.setAlignmentY(0.0F);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 265, -1));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/zodiac128/leao128px.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(16, 16, 16, 16, new javax.swing.ImageIcon(getClass().getResource("/img/Icons/stars16px.png")))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbName.setText("Nome:");
        jPanel1.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtName.setText("awddwdawdwad");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 159, 260, 30));

        lbGenre.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbGenre.setText("Gênero:");
        jPanel1.add(lbGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtBornDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtBornDate.setText("12/01/2022");
        txtBornDate.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtBornDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtBornDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 30));

        jTextPane1.setBackground(new java.awt.Color(51, 147, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 340, 100));

        btnConsult.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnConsult.setText("Consultar Horóscopo");
        btnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btngGeneros.add(rbtFemale);
        rbtFemale.setText("Feminino");
        jPanel1.add(rbtFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        btngGeneros.add(rbtMale);
        rbtMale.setText("Masculino");
        rbtMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lbBornDate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbBornDate.setText("Data de nascimento:");
        jPanel1.add(lbBornDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBornDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornDateActionPerformed

    private void rbtMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMaleActionPerformed

    private void btnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultActionPerformed
        
    }//GEN-LAST:event_btnConsultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.ButtonGroup btngGeneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbBornDate;
    private javax.swing.JLabel lbGenre;
    private javax.swing.JLabel lbName;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JFormattedTextField txtBornDate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
